# Generated by Django 3.2.18 on 2023-03-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
